[package]
name = "blimy-github"
version = "0.1.0"
repository = "https://github.com/antan2002/blimy"
homepage = "https://github.com/antan2002/blimy#readme"
authors = ["antan2002 <antanroy502@gmail.com>"]
license = "AGPL-3.0"
edition = "2024"

[dependencies]
blimy-exec-path = { path = "../exec-path" }
git2 = { version = "0.20", features = ["vendored-libgit2", "vendored-openssl"] }
log = "0.4"
reqwest = { version = "0.12", default-features = false, features = [
  "blocking",
  "json",
  "rustls-tls",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
