BLIMY_ZDOTDIR="$ZDOTDIR"
ZDOTDIR="$BLIMY_USER_ZDOTDIR"
if [[ -f "$ZDOTDIR/.zlogin" ]]; then
  builtin source "$ZDOTDIR/.zlogin"
fi
# Leave the user's ZDOTDIR in place for subshells now that startup is done.
unset BLIMY_ZDOTDIR
