blimy_ZDOTDIR="$ZDOTDIR"
ZDOTDIR="$blimy_USER_ZDOTDIR"
if [[ -f "$ZDOTDIR/.zshrc" ]]; then
  builtin source "$ZDOTDIR/.zshrc"
fi
ZDOTDIR="$blimy_ZDOTDIR"
builtin source "$blimy_ZDOTDIR/blimy-shell-integration.zsh"
