BLIMY_ZDOTDIR="$ZDOTDIR"
ZDOTDIR="$BLIMY_USER_ZDOTDIR"
if [[ -f "$ZDOTDIR/.zshrc" ]]; then
  builtin source "$ZDOTDIR/.zshrc"
fi
ZDOTDIR="$BLIMY_ZDOTDIR"
builtin source "$BLIMY_ZDOTDIR/Blimy-shell-integration.zsh"
